#!/bin/sh
# Print spin_limits.h: the drivers' spin limits, read from their own sources so the report's
# "this wait can last N ms" stays true when a limit changes. Fails if any is missing.
#
#   sh spin_limits.sh ../agent > build/spin_limits.h
set -eu
AGENT=$1

limit() {
    # $1 name here, $2 source file, $3 macro there
    value=$(sed -n "s/^#define $3 \([0-9][0-9]*u\{0,1\}\).*/\1/p" "$AGENT/$2" | tr -d '\r')
    if [ -z "$value" ]; then
        echo "spin_limits.sh: no '#define $3' in $AGENT/$2" >&2
        exit 1
    fi
    echo "#define $1 $value"
}

echo "/* Generated by spin_limits.sh from n64/agent. Do not edit. */"
limit SPIN_PI_WAIT pi_io.c PI_WAIT_SPINS
limit SPIN_ED_BUSY ed64.c ED_BUSY_SPINS
limit SPIN_SC64_CMD sc64.c SC64_CMD_SPINS
limit SPIN_PRO_STATUS ed64pro.c STATUS_SPINS
limit SPIN_PRO_MCU ed64pro.c MCU_SPINS
